baseurl: /apcsa-notes
title: Computer Science A
subtitle: Notes for AP Computer Science A - 2022-23
author: Charlie Sokolove
simple_search: http://google.com/search
description: Notes for AP Computer Science A - 2022-23
name: apcsa-notes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/New_York
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: vscode
git:
  branch: main
transfer:
  command: rsync
  settings: -av
  source: _site/
